[package]
name = "web_based_desktop_app"
version = "0.1.0"
authors = ["Santo Kalayil"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.7.2"
askama = "0.8"
